#!/bin/sh
set -eu

# Param 1 is the feature name
FEATURE_NAME="$1"

GIT_ROOT="$(git rev-parse --show-toplevel)"

cp "${GIT_ROOT}/src/_common/common.sh" "${GIT_ROOT}/src/${FEATURE_NAME}/common.sh"

devcontainer \
  features test \
  --skip-autogenerated . \
  --features "${FEATURE_NAME}"
