#!/bin/sh
set -eu

GIT_ROOT="$(git rev-parse --show-toplevel)"

cp "${GIT_ROOT}/src/_common/common.sh" "${GIT_ROOT}/src/sphinx-needs/common.sh"

devcontainer \
  features test \
  --skip-autogenerated . \
  --features sphinx-needs
